# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  openfrontendbe:
    image: openfrontendbe
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7145:7145
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
